### ISSUE TITLE
locate_blocks returned a result with an error set

### ISSUE THREAD

**Issue by alvra** [Kronuz/pyScss#365]
Found an error with `@content` on Python3.6. Here's how to reproduce it.

```
@mixin test() {
    @content;
}

@include test();
```

```
$ python3.6 -m pip install --no-cache-dir pyscss==1.3.5
Collecting pyscss==1.3.5
  Downloading pyScss-1.3.5.tar.gz (123kB)
    100% |████████████████████████████████| 133kB 4.8MB/s 
Requirement already satisfied: six in ./lib/python3.6/site-packages (from pyscss==1.3.5)
Installing collected packages: pyscss
  Running setup.py install for pyscss ... done
Successfully installed pyscss-1.3.5

$ pyscss style.scss
TypeError: argument 1 must be str, not None

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/tmp/csstest/py36/lib/python3.6/site-packages/scss/compiler.py", line 349, in manage_children
    self._manage_children_impl(rule, scope)
  File "/tmp/csstest/py36/lib/python3.6/site-packages/scss/compiler.py", line 359, in _manage_children_impl
    for c_lineno, c_property, c_codestr in locate_blocks(rule.unparsed_contents):
SystemError: <built-in function locate_blocks> returned a result with an error set

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/csstest/py36/bin/pyscss", line 11, in <module>
    load_entry_point('pyScss==1.3.5', 'console_scripts', 'pyscss')()
  File "/tmp/csstest/py36/lib/python3.6/site-packages/scss/tool.py", line 145, in main
    do_build(options, args)
  File "/tmp/csstest/py36/lib/python3.6/site-packages/scss/tool.py", line 193, in do_build
    output = css.compile(source_files=source_files)
  File "/tmp/csstest/py36/lib/python3.6/site-packages/scss/legacy.py", line 189, in compile
    compiled = compiler.call_and_catch_errors(compilation.run)
  File "/tmp/csstest/py36/lib/python3.6/site-packages/scss/compiler.py", line 176, in call_and_catch_errors
    return f(*args, **kwargs)
  File "/tmp/csstest/py36/lib/python3.6/site-packages/scss/compiler.py", line 296, in run
    self.manage_children(rule, scope=None)
  File "/tmp/csstest/py36/lib/python3.6/site-packages/scss/compiler.py", line 349, in manage_children
    self._manage_children_impl(rule, scope)
  File "/tmp/csstest/py36/lib/python3.6/site-packages/scss/compiler.py", line 378, in _manage_children_impl
    method(calculator, rule, scope, block)
  File "/tmp/csstest/py36/lib/python3.6/site-packages/scss/compiler.py", line 778, in _at_include
    self.manage_children(_rule, scope)
  File "/tmp/csstest/py36/lib/python3.6/site-packages/scss/compiler.py", line 349, in manage_children
    self._manage_children_impl(rule, scope)
  File "/tmp/csstest/py36/lib/python3.6/site-packages/scss/compiler.py", line 378, in _manage_children_impl
    method(calculator, rule, scope, block)
  File "/tmp/csstest/py36/lib/python3.6/site-packages/scss/compiler.py", line 788, in _at_content
    self.manage_children(rule, scope)
  File "/tmp/csstest/py36/lib/python3.6/site-packages/scss/compiler.py", line 354, in manage_children
    raise SassError(e, rule=rule)
scss.errors.SassError: <built-in function locate_blocks> returned a result with an error set
```

I'm running Python3.6, and I noticed the C speedups weren't installed. The error does not occur on Python3.4 with C speedups.

**Comment by alvra** [comment]
Looking further into this, I've managed to reproduce the problem on python2.7 as well.
It seems it occurs when having a mixin with @content, but not passing a content block to @include.

Traceback of the error on python 2.7.

```
$ python -m scss bug.scss
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/site-packages/scss/__main__.py", line 3, in <module>
    scss.tool.main()
  File "/usr/local/lib/python2.7/site-packages/scss/tool.py", line 145, in main
    do_build(options, args)
  File "/usr/local/lib/python2.7/site-packages/scss/tool.py", line 193, in do_build
    output = css.compile(source_files=source_files)
  File "/usr/local/lib/python2.7/site-packages/scss/legacy.py", line 189, in compile
    compiled = compiler.call_and_catch_errors(compilation.run)
  File "/usr/local/lib/python2.7/site-packages/scss/compiler.py", line 176, in call_and_catch_errors
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/scss/compiler.py", line 296, in run
    self.manage_children(rule, scope=None)
  File "/usr/local/lib/python2.7/site-packages/scss/compiler.py", line 349, in manage_children
    self._manage_children_impl(rule, scope)
  File "/usr/local/lib/python2.7/site-packages/scss/compiler.py", line 378, in _manage_children_impl
    method(calculator, rule, scope, block)
  File "/usr/local/lib/python2.7/site-packages/scss/compiler.py", line 778, in _at_include
    self.manage_children(_rule, scope)
  File "/usr/local/lib/python2.7/site-packages/scss/compiler.py", line 349, in manage_children
    self._manage_children_impl(rule, scope)
  File "/usr/local/lib/python2.7/site-packages/scss/compiler.py", line 378, in _manage_children_impl
    method(calculator, rule, scope, block)
  File "/usr/local/lib/python2.7/site-packages/scss/compiler.py", line 788, in _at_content
    self.manage_children(rule, scope)
  File "/usr/local/lib/python2.7/site-packages/scss/compiler.py", line 354, in manage_children
    raise SassError(e, rule=rule)
scss.errors.SassError: expected string or buffer
```
