### ISSUE TITLE
When testing django-pyscss I get crash in _scanner.so

### ISSUE THREAD

**Issue by mcepl** [Kronuz/pyScss#378]
While building python-django-pyscss (see [build log](https://github.com/Kronuz/pyScss/files/2773597/log.txt)) I get a crash which I was able to catch in ``_scanner.so``:
```
#0  0x00007ffff75ed08b in raise () from /lib64/libc.so.6
#1  0x00007ffff75d64e9 in abort () from /lib64/libc.so.6
#2  0x00007ffff762f9a7 in __libc_message () from /lib64/libc.so.6
#3  0x00007ffff7635e9c in malloc_printerr () from /lib64/libc.so.6
#4  0x00007ffff7639c5e in free_check.part () from /lib64/libc.so.6
#5  0x00007ffff3bdbbb4 in Hashtable_del ()
   from /usr/lib64/python2.7/site-packages/scss/grammar/_scanner.so
#6  0x00007ffff3bdb2a5 in Scanner_del ()
   from /usr/lib64/python2.7/site-packages/scss/grammar/_scanner.so
#7  0x00007ffff3bda1c2 in ?? ()
   from /usr/lib64/python2.7/site-packages/scss/grammar/_scanner.so
```

**Comment by mcepl** [comment]
OK, there is a better backtrace here:
```
[    5s] Executing(%check): /bin/sh -e /var/tmp/rpm-tmp.khfwrN
[    5s] + umask 022
[    5s] + cd /home/abuild/rpmbuild/BUILD
[    5s] + cd django-pyscss-2.0.2
[    5s] ++ '[' -f _current_flavor ']'
[    5s] ++ cat _current_flavor
[    5s] + python_flavor=python3
[    5s] + '[' -z python3 ']'
[    5s] + '[' python3 '!=' python2 ']'
[    5s] + '[' -d build ']'
[    5s] + mv build _build.python3
[    5s] + '[' -d _build.python2 ']'
[    5s] + mv _build.python2 build
[    5s] + echo python2
[    5s] + /usr/bin/python2 setup.py test -v
[    5s] running test
[    5s] running egg_info
[    5s] writing requirements to django_pyscss.egg-info/requires.txt
[    5s] writing django_pyscss.egg-info/PKG-INFO
[    5s] writing top-level names to django_pyscss.egg-info/top_level.txt
[    5s] writing dependency_links to django_pyscss.egg-info/dependency_links.txt
[    6s] reading manifest file 'django_pyscss.egg-info/SOURCES.txt'
[    6s] reading manifest template 'MANIFEST.in'
[    6s] warning: no previously-included files matching '*.pyc' found under directory 'tests'
[    6s] warning: no previously-included files matching '*.pyc' found under directory 'testproject'
[    6s] writing manifest file 'django_pyscss.egg-info/SOURCES.txt'
[    6s] running build_ext
[    6s] System check identified some issues:
[    6s] 
[    6s] WARNINGS:
[    6s] ?: (1_10.W001) The MIDDLEWARE_CLASSES setting is deprecated in Django 1.10 and the MIDDLEWARE setting takes precedence. Since you've set MIDDLEWARE, the value of MIDDLEWARE_CLASSES is ignored.
[    6s] 
[    6s] System check identified 1 issue (0 silenced).
[    8s] free(): invalid pointer
[    8s] /var/tmp/rpm-tmp.khfwrN: line 38: 21039 Aborted                 (core dumped) /usr/bin/python2 setup.py test -v
[    8s] error: Bad exit status from /var/tmp/rpm-tmp.khfwrN (%check)
[    8s] 
[    8s] 
[    8s] RPM build errors:
[    8s]     Bad exit status from /var/tmp/rpm-tmp.khfwrN (%check)
[    8s] 
[    8s] stitny failed "build python-django-pyscss.spec" at Fri Jan 18 16:00:09 UTC 2019.
[    8s] 

The buildroot was: /var/tmp/build-root/openSUSE_Tumbleweed-x86_64
matej@stitny: python-django-pyscss$ osc chroot
mounting proc: sudo mount -n -tproc none /var/tmp/build-root/openSUSE_Tumbleweed-x86_64/proc
mounting sys: sudo mount -n -tsysfs none /var/tmp/build-root/openSUSE_Tumbleweed-x86_64/sys
mounting devpts: sudo mount -n -tdevpts -omode=0620,gid=5 none /var/tmp/build-root/openSUSE_Tumbleweed-x86_64/dev/pts
running: sudo chroot /var/tmp/build-root/openSUSE_Tumbleweed-x86_64 su - abuild
abuild@stitny:~> rpm -q gdb
gdb-8.2-2.1.x86_64
abuild@stitny:~> cd rpmbuild/BUILD/django-pyscss-2.0.2/
abuild@stitny:~/rpmbuild/BUILD/django-pyscss-2.0.2> 
abuild@stitny:~/rpmbuild/BUILD/django-pyscss-2.0.2> gdb python2
GNU gdb (GDB; openSUSE Tumbleweed) 8.2
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-suse-linux".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://bugs.opensuse.org/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from python2...Missing separate debuginfo for /usr/bin/python2.7
Try: zypper install -C "debuginfo(build-id)=820a996ac193f858f25e5b08407f20bf54613c92"
(no debugging symbols found)...done.
(gdb) run setup.py test -v
































(gdb) run setup.py test -v
Starting program: /usr/bin/python2 setup.py test -v
Missing separate debuginfo for /lib64/ld-linux-x86-64.so.2
Try: zypper install -C "debuginfo(build-id)=d1f6bf237ba196265561924d1baaf522e036281f"
Missing separate debuginfo for /usr/lib64/libpython2.7.so.1.0
Try: zypper install -C "debuginfo(build-id)=6ae596df1955b542b301248bc71f0b25593310e3"
Missing separate debuginfo for /lib64/libpthread.so.0
Try: zypper install -C "debuginfo(build-id)=b5ad7ea10e4e88d4e2cc038e5c3288bdea82e20b"
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Missing separate debuginfo for /lib64/libc.so.6
Try: zypper install -C "debuginfo(build-id)=5926416cd74d1dfe53d37374041bca37ee80c598"
Missing separate debuginfo for /lib64/libdl.so.2
Try: zypper install -C "debuginfo(build-id)=b21e9d59d1465db80fa52e72a4803f1901202e6d"
Missing separate debuginfo for /lib64/libutil.so.1
Try: zypper install -C "debuginfo(build-id)=525cdccf6764fc1155301d36c34af1d43385d687"
Missing separate debuginfo for /lib64/libm.so.6
Try: zypper install -C "debuginfo(build-id)=1fc13b3ef7db0024a3f401933c6da8b266a8e06c"
Missing separate debuginfo for /usr/lib64/python2.7/lib-dynload/_locale.so
Try: zypper install -C "debuginfo(build-id)=3bd966aa95ab2f65a0d4a07fb4fc10e9a747f0d9"
Missing separate debuginfo for /usr/lib64/python2.7/lib-dynload/_functools.so
Try: zypper install -C "debuginfo(build-id)=8965db4a0904f7f37324c285382f4ad5c120a287"
Missing separate debuginfo for /usr/lib64/python2.7/lib-dynload/strop.so
Try: zypper install -C "debuginfo(build-id)=c7db44f64065fb60cc7972d723773b4a32f2431e"
Missing separate debuginfo for /usr/lib64/python2.7/lib-dynload/grp.so
Try: zypper install -C "debuginfo(build-id)=ab05a08bbcdb6d0d8a198d9f3a277a72d7c6360f"
Missing separate debuginfo for /usr/lib64/python2.7/lib-dynload/_collections.so
Try: zypper install -C "debuginfo(build-id)=bb4facffb0e5012e7ab59cb559ef3e41a1500470"
Missing separate debuginfo for /usr/lib64/python2.7/lib-dynload/operator.so
Try: zypper install -C "debuginfo(build-id)=c63a95dcc88db51a4b7eb097016b4e966dd858c2"
Missing separate debuginfo for /usr/lib64/python2.7/lib-dynload/itertools.so
Try: zypper install -C "debuginfo(build-id)=ab6b26567166efd8d1d172893e551eed0cd7878f"
Missing separate debuginfo for /usr/lib64/python2.7/lib-dynload/_heapq.so
Try: zypper install -C "debuginfo(build-id)=8129c567300fbb833b1e2c3bc471e8c3e61791ed"
Missing separate debuginfo for /usr/lib64/python2.7/lib-dynload/_io.so
Try: zypper install -C "debuginfo(build-id)=79f9304c55460429daec407b861e43ff0d35e7c1"
Missing separate debuginfo for /usr/lib64/python2.7/lib-dynload/time.so
Try: zypper install -C "debuginfo(build-id)=1ec135782f92ea906634ff08e352f90bb2b9e273"
Missing separate debuginfo for /usr/lib64/python2.7/lib-dynload/_struct.so
Try: zypper install -C "debuginfo(build-id)=82b520e0341a01b08d4e1b9b7fd506e36fd46f6e"
Missing separate debuginfo for /usr/lib64/python2.7/lib-dynload/zlib.so
Try: zypper install -C "debuginfo(build-id)=aa8c96cc2a7e33dff36990a02baf4c4da85618f8"
Missing separate debuginfo for /lib64/libz.so.1
Try: zypper install -C "debuginfo(build-id)=3dc027b3dce93bdbf0b095b682d942b952c173a2"
Missing separate debuginfo for /usr/lib64/python2.7/lib-dynload/bz2.so
Try: zypper install -C "debuginfo(build-id)=19cfea25c67ffa72f3b785a5ee8457b60f9bf9e3"
Missing separate debuginfo for /usr/lib64/libbz2.so.1
Try: zypper install -C "debuginfo(build-id)=c30bc4f9bccce72a8fa5b6880f6dc2fa6e9eb61e"
Missing separate debuginfo for /usr/lib64/python2.7/lib-dynload/binascii.so
Try: zypper install -C "debuginfo(build-id)=89168cdfc0b4f3fb4b97a199a0e350f3a0d0892e"
Missing separate debuginfo for /usr/lib64/python2.7/lib-dynload/cStringIO.so
Try: zypper install -C "debuginfo(build-id)=66c26054abb985d9de286c9d3b9b34eb483dcf3f"
Missing separate debuginfo for /usr/lib64/python2.7/lib-dynload/datetime.so
Try: zypper install -C "debuginfo(build-id)=faac3459a01a258ce0a9c39ef0bb1cdcca974144"
Missing separate debuginfo for /usr/lib64/python2.7/lib-dynload/math.so
Try: zypper install -C "debuginfo(build-id)=5d4433c64e7d47c1b5ae4d0a0311e850e3340c00"
Missing separate debuginfo for /usr/lib64/python2.7/lib-dynload/_hashlib.so
Try: zypper install -C "debuginfo(build-id)=d4dbe44050e60f1ba82863e2e4e5e250fc029c8b"
Missing separate debuginfo for /usr/lib64/libcrypto.so.1.1
Try: zypper install -C "debuginfo(build-id)=d4db28b074ea8455fb9e6351317e8b2469a7c984"
Missing separate debuginfo for /usr/lib64/python2.7/lib-dynload/_random.so
Try: zypper install -C "debuginfo(build-id)=601ac0d7c2a14461f9859af3979a88091f746b09"
Missing separate debuginfo for /usr/lib64/python2.7/lib-dynload/_socket.so
Try: zypper install -C "debuginfo(build-id)=e026a59ce4c2038b4b1904ad85925abdb9ab9d58"
Missing separate debuginfo for /usr/lib64/python2.7/lib-dynload/_ssl.so
Try: zypper install -C "debuginfo(build-id)=eb57d497ebfaef9e30b55d5829ee3b66bd0320f1"
Missing separate debuginfo for /usr/lib64/libssl.so.1.1
Try: zypper install -C "debuginfo(build-id)=45d4ea32eebe688bc69d4ff385b29dbbceba6d48"
Missing separate debuginfo for /usr/lib64/python2.7/lib-dynload/fcntl.so
Try: zypper install -C "debuginfo(build-id)=ccc2b614749ca5d774e7e4115a59e8fca56d3040"
Missing separate debuginfo for /usr/lib64/python2.7/lib-dynload/array.so
Try: zypper install -C "debuginfo(build-id)=ce3b184d4132cf57b7f2c3392efe06ce15ea9a04"
Missing separate debuginfo for /usr/lib64/python2.7/lib-dynload/_ctypes.so
Try: zypper install -C "debuginfo(build-id)=6950493052145c62f15dd592b57d7fb3a42779d3"
[Detaching after fork from child process 21138]
Missing separate debuginfo for /usr/lib64/python2.7/lib-dynload/select.so
Try: zypper install -C "debuginfo(build-id)=9963256624669ca71956fb39eee6b61141d733ad"
running test
running egg_info
Missing separate debuginfo for /usr/lib64/python2.7/lib-dynload/unicodedata.so
Try: zypper install -C "debuginfo(build-id)=5a610264d36494f12253114cbdf5f417437b7fb5"
writing requirements to django_pyscss.egg-info/requires.txt
writing django_pyscss.egg-info/PKG-INFO
writing top-level names to django_pyscss.egg-info/top_level.txt
writing dependency_links to django_pyscss.egg-info/dependency_links.txt
Missing separate debuginfo for /usr/lib64/python2.7/lib-dynload/_json.so
Try: zypper install -C "debuginfo(build-id)=335e7d0b14ff4babb8f6519c764dea4380d7b555"
reading manifest file 'django_pyscss.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'django_pyscss.egg-info/SOURCES.txt'
running build_ext
Missing separate debuginfo for /usr/lib64/python2.7/lib-dynload/cPickle.so
Try: zypper install -C "debuginfo(build-id)=0ab083dbb8872b0ef324c05c15f30111e4b79f1d"
Missing separate debuginfo for /usr/lib64/python2.7/lib-dynload/_bisect.so
Try: zypper install -C "debuginfo(build-id)=133b92dec54d4c4fb70a94cf4345fd1b58e15b3c"
[Detaching after fork from child process 21144]
Missing separate debuginfo for /usr/lib64/libuuid.so.1
Try: zypper install -C "debuginfo(build-id)=08a0fcf899e26749220cdb05df1aef09d53693fe"
Missing separate debuginfo for /usr/lib64/python2.7/site-packages/markupsafe/_speedups.so
Try: zypper install -C "debuginfo(build-id)=01c2ae5bf2455fcd4fde813a9923cb1eee8bef4f"
Missing separate debuginfo for /usr/lib64/python2.7/site-packages/PIL/_imaging.so
Try: zypper install -C "debuginfo(build-id)=a290c82ebae1e7607758231fac7bcd350898f293"
Missing separate debuginfo for /usr/lib64/libjpeg.so.8
Try: zypper install -C "debuginfo(build-id)=fe13d0b2d03f4354796caee561fe6fd61fd4c9e3"
Missing separate debuginfo for /usr/lib64/libopenjp2.so.7
Try: zypper install -C "debuginfo(build-id)=c2611587fff28bbf81def1846af79b82c038d21c"
Missing separate debuginfo for /usr/lib64/libtiff.so.5
Try: zypper install -C "debuginfo(build-id)=01ee05f13d8a593aff665df4762348f400cea168"
Missing separate debuginfo for /usr/lib64/liblzma.so.5
Try: zypper install -C "debuginfo(build-id)=95f262a4ff78ab4d413cbc92ecfabcb50c542a6e"
Missing separate debuginfo for /usr/lib64/libjbig.so.2
Try: zypper install -C "debuginfo(build-id)=b9c7cdc140d6cddb8bce9d6691ee9983c2acea32"
Missing separate debuginfo for /usr/lib64/python2.7/lib-dynload/mmap.so
Try: zypper install -C "debuginfo(build-id)=8fecc0e7a6eee06bf74e2ed157b2208604b2b80f"
Missing separate debuginfo for /usr/lib64/python2.7/site-packages/PIL/_webp.so
Try: zypper install -C "debuginfo(build-id)=93f89d436695bb43722e44583064fd9c776fb555"
Missing separate debuginfo for /usr/lib64/libwebp.so.7
Try: zypper install -C "debuginfo(build-id)=fa58a2e7dc0b3978621d908b103a23b72bc4342c"
Missing separate debuginfo for /usr/lib64/libwebpmux.so.3
Try: zypper install -C "debuginfo(build-id)=b3ab7323048211b06f34a083540d306afcc00bd6"
Missing separate debuginfo for /usr/lib64/libwebpdemux.so.2
Try: zypper install -C "debuginfo(build-id)=97a0b06942b74a9cee5a53660c4dfc1c9cf1b6dc"
Missing separate debuginfo for /usr/lib64/python2.7/lib-dynload/termios.so
Try: zypper install -C "debuginfo(build-id)=eb721f1b18a11251ecd6e6cc111f09b037cf4e73"
Missing separate debuginfo for /usr/lib64/python2.7/lib-dynload/_sqlite3.so
Try: zypper install -C "debuginfo(build-id)=5265ed1f571bf6a6827af95589dd5605d81b742e"
Missing separate debuginfo for /usr/lib64/libsqlite3.so.0
Try: zypper install -C "debuginfo(build-id)=544dadb4118c21b3befeac210cbed5dd6c51665f"
Missing separate debuginfo for /usr/lib64/python2.7/lib-dynload/_multiprocessing.so
Try: zypper install -C "debuginfo(build-id)=8e9d12152baaacd6e7761c86e3f336a7f3e9b6ae"
Missing separate debuginfo for /usr/lib64/libpcre.so.1
Try: zypper install -C "debuginfo(build-id)=d0323c9df737a832d618529777e2c95dc0119be1"
Creating test database for alias 'default'...
Missing separate debuginfo for /usr/lib64/python2.7/lib-dynload/pyexpat.so
Try: zypper install -C "debuginfo(build-id)=f877a1782bb390da8a858ea5f0852e7f34aa618f"
System check identified some issues:

WARNINGS:
?: (1_10.W001) The MIDDLEWARE_CLASSES setting is deprecated in Django 1.10 and the MIDDLEWARE setting takes precedence. Since you've set MIDDLEWARE, the value of MIDDLEWARE_CLASSES is ignored.

System check identified 1 issue (0 silenced).
free(): invalid pointer

Program received signal SIGABRT, Aborted.
0x00007ffff75ed08b in raise () from /lib64/libc.so.6
(gdb) t a a bt
(gdb) t a a bt

Thread 1 (Thread 0x7ffff7ff14c0 (LWP 21134)):
#0  0x00007ffff75ed08b in raise () from /lib64/libc.so.6
#1  0x00007ffff75d64e9 in abort () from /lib64/libc.so.6
#2  0x00007ffff762f9a7 in __libc_message () from /lib64/libc.so.6
#3  0x00007ffff7635e9c in malloc_printerr () from /lib64/libc.so.6
#4  0x00007ffff7639c5e in free_check.part () from /lib64/libc.so.6
#5  0x00007ffff3bdbbb4 in Hashtable_del (hashtable=0x5555596d79a0) at scss/src/hashtable.c:125
#6  0x00007ffff3bdb2a5 in Scanner_del (self=0x555559464f00) at scss/src/scanner.c:277
#7  0x00007ffff3bda1c2 in scss_Scanner_dealloc (self=0x7ffff3743410) at scss/src/_speedups.c:434
#8  0x00007ffff7c734d3 in ?? () from /usr/lib64/libpython2.7.so.1.0
#9  0x00007ffff7c56c3c in ?? () from /usr/lib64/libpython2.7.so.1.0
#10 0x00007ffff7c734b0 in ?? () from /usr/lib64/libpython2.7.so.1.0
#11 0x00007ffff7c41097 in ?? () from /usr/lib64/libpython2.7.so.1.0
#12 0x00007ffff7c93949 in PyEval_EvalCodeEx () from /usr/lib64/libpython2.7.so.1.0
#13 0x00007ffff7c99d44 in PyEval_EvalFrameEx () from /usr/lib64/libpython2.7.so.1.0
#14 0x00007ffff7c9392c in PyEval_EvalCodeEx () from /usr/lib64/libpython2.7.so.1.0
#15 0x00007ffff7c99d44 in PyEval_EvalFrameEx () from /usr/lib64/libpython2.7.so.1.0
#16 0x00007ffff7c9392c in PyEval_EvalCodeEx () from /usr/lib64/libpython2.7.so.1.0
#17 0x00007ffff7c9a203 in PyEval_EvalFrameEx () from /usr/lib64/libpython2.7.so.1.0
#18 0x00007ffff7c9392c in PyEval_EvalCodeEx () from /usr/lib64/libpython2.7.so.1.0
#19 0x00007ffff7c9a203 in PyEval_EvalFrameEx () from /usr/lib64/libpython2.7.so.1.0
#20 0x00007ffff7c9392c in PyEval_EvalCodeEx () from /usr/lib64/libpython2.7.so.1.0
#21 0x00007ffff7c9a203 in PyEval_EvalFrameEx () from /usr/lib64/libpython2.7.so.1.0
#22 0x00007ffff7c9392c in PyEval_EvalCodeEx () from /usr/lib64/libpython2.7.so.1.0
#23 0x00007ffff7c4192f in ?? () from /usr/lib64/libpython2.7.so.1.0
#24 0x00007ffff7c2a1f3 in PyObject_Call () from /usr/lib64/libpython2.7.so.1.0
#25 0x00007ffff7c97666 in PyEval_EvalFrameEx () from /usr/lib64/libpython2.7.so.1.0
#26 0x00007ffff7c9392c in PyEval_EvalCodeEx () from /usr/lib64/libpython2.7.so.1.0
#27 0x00007ffff7c9a203 in PyEval_EvalFrameEx () from /usr/lib64/libpython2.7.so.1.0
#28 0x00007ffff7c9392c in PyEval_EvalCodeEx () from /usr/lib64/libpython2.7.so.1.0
#29 0x00007ffff7c99d44 in PyEval_EvalFrameEx () from /usr/lib64/libpython2.7.so.1.0
#30 0x00007ffff7c9392c in PyEval_EvalCodeEx () from /usr/lib64/libpython2.7.so.1.0
#31 0x00007ffff7c4192f in ?? () from /usr/lib64/libpython2.7.so.1.0
#32 0x00007ffff7c2a1f3 in PyObject_Call () from /usr/lib64/libpython2.7.so.1.0
#33 0x00007ffff7c97666 in PyEval_EvalFrameEx () from /usr/lib64/libpython2.7.so.1.0
#34 0x00007ffff7c9392c in PyEval_EvalCodeEx () from /usr/lib64/libpython2.7.so.1.0
#35 0x00007ffff7c4192f in ?? () from /usr/lib64/libpython2.7.so.1.0
#36 0x00007ffff7c2a1f3 in PyObject_Call () from /usr/lib64/libpython2.7.so.1.0
#37 0x00007ffff7c97666 in PyEval_EvalFrameEx () from /usr/lib64/libpython2.7.so.1.0
#38 0x00007ffff7c3a525 in ?? () from /usr/lib64/libpython2.7.so.1.0
#39 0x00007ffff7c955bf in PyEval_EvalFrameEx () from /usr/lib64/libpython2.7.so.1.0
#40 0x00007ffff7c9392c in PyEval_EvalCodeEx () from /usr/lib64/libpython2.7.so.1.0
#41 0x00007ffff7c99d44 in PyEval_EvalFrameEx () from /usr/lib64/libpython2.7.so.1.0
#42 0x00007ffff7c9392c in PyEval_EvalCodeEx () from /usr/lib64/libpython2.7.so.1.0
#43 0x00007ffff7c4192f in ?? () from /usr/lib64/libpython2.7.so.1.0
#44 0x00007ffff7c2a1f3 in PyObject_Call () from /usr/lib64/libpython2.7.so.1.0
#45 0x00007ffff7c97666 in PyEval_EvalFrameEx () from /usr/lib64/libpython2.7.so.1.0
#46 0x00007ffff7c9392c in PyEval_EvalCodeEx () from /usr/lib64/libpython2.7.so.1.0
#47 0x00007ffff7c4192f in ?? () from /usr/lib64/libpython2.7.so.1.0
#48 0x00007ffff7c2a1f3 in PyObject_Call () from /usr/lib64/libpython2.7.so.1.0
--Type <RET> for more, q to quit, c to continue without paging--
#49 0x00007ffff7c97666 in PyEval_EvalFrameEx () from /usr/lib64/libpython2.7.so.1.0
#50 0x00007ffff7c9392c in PyEval_EvalCodeEx () from /usr/lib64/libpython2.7.so.1.0
#51 0x00007ffff7c9a203 in PyEval_EvalFrameEx () from /usr/lib64/libpython2.7.so.1.0
#52 0x00007ffff7c9392c in PyEval_EvalCodeEx () from /usr/lib64/libpython2.7.so.1.0
#53 0x00007ffff7c99d44 in PyEval_EvalFrameEx () from /usr/lib64/libpython2.7.so.1.0
#54 0x00007ffff7c9392c in PyEval_EvalCodeEx () from /usr/lib64/libpython2.7.so.1.0
#55 0x00007ffff7c99d44 in PyEval_EvalFrameEx () from /usr/lib64/libpython2.7.so.1.0
#56 0x00007ffff7c9392c in PyEval_EvalCodeEx () from /usr/lib64/libpython2.7.so.1.0
#57 0x00007ffff7c9a203 in PyEval_EvalFrameEx () from /usr/lib64/libpython2.7.so.1.0
#58 0x00007ffff7c9392c in PyEval_EvalCodeEx () from /usr/lib64/libpython2.7.so.1.0
#59 0x00007ffff7c9a203 in PyEval_EvalFrameEx () from /usr/lib64/libpython2.7.so.1.0
#60 0x00007ffff7c94f37 in PyEval_EvalFrameEx () from /usr/lib64/libpython2.7.so.1.0
#61 0x00007ffff7c9392c in PyEval_EvalCodeEx () from /usr/lib64/libpython2.7.so.1.0
#62 0x00007ffff7c9a203 in PyEval_EvalFrameEx () from /usr/lib64/libpython2.7.so.1.0
#63 0x00007ffff7c94f37 in PyEval_EvalFrameEx () from /usr/lib64/libpython2.7.so.1.0
#64 0x00007ffff7c9392c in PyEval_EvalCodeEx () from /usr/lib64/libpython2.7.so.1.0
#65 0x00007ffff7c4192f in ?? () from /usr/lib64/libpython2.7.so.1.0
#66 0x00007ffff7c2a1f3 in PyObject_Call () from /usr/lib64/libpython2.7.so.1.0
#67 0x00007ffff7c97666 in PyEval_EvalFrameEx () from /usr/lib64/libpython2.7.so.1.0
#68 0x00007ffff7c9392c in PyEval_EvalCodeEx () from /usr/lib64/libpython2.7.so.1.0
#69 0x00007ffff7c9a203 in PyEval_EvalFrameEx () from /usr/lib64/libpython2.7.so.1.0
#70 0x00007ffff7c9392c in PyEval_EvalCodeEx () from /usr/lib64/libpython2.7.so.1.0
#71 0x00007ffff7c4179e in ?? () from /usr/lib64/libpython2.7.so.1.0
#72 0x00007ffff7c2a1f3 in PyObject_Call () from /usr/lib64/libpython2.7.so.1.0
#73 0x00007ffff7c34fb6 in ?? () from /usr/lib64/libpython2.7.so.1.0
#74 0x00007ffff7c2a1f3 in PyObject_Call () from /usr/lib64/libpython2.7.so.1.0
#75 0x00007ffff7ce9987 in ?? () from /usr/lib64/libpython2.7.so.1.0
#76 0x00007ffff7c2a1f3 in PyObject_Call () from /usr/lib64/libpython2.7.so.1.0
#77 0x00007ffff7c99c05 in PyEval_EvalFrameEx () from /usr/lib64/libpython2.7.so.1.0
#78 0x00007ffff7c9392c in PyEval_EvalCodeEx () from /usr/lib64/libpython2.7.so.1.0
#79 0x00007ffff7c4192f in ?? () from /usr/lib64/libpython2.7.so.1.0
#80 0x00007ffff7c2a1f3 in PyObject_Call () from /usr/lib64/libpython2.7.so.1.0
#81 0x00007ffff7c97666 in PyEval_EvalFrameEx () from /usr/lib64/libpython2.7.so.1.0
#82 0x00007ffff7c9392c in PyEval_EvalCodeEx () from /usr/lib64/libpython2.7.so.1.0
#83 0x00007ffff7c4179e in ?? () from /usr/lib64/libpython2.7.so.1.0
#84 0x00007ffff7c2a1f3 in PyObject_Call () from /usr/lib64/libpython2.7.so.1.0
#85 0x00007ffff7c34fb6 in ?? () from /usr/lib64/libpython2.7.so.1.0
#86 0x00007ffff7c2a1f3 in PyObject_Call () from /usr/lib64/libpython2.7.so.1.0
#87 0x00007ffff7ce9987 in ?? () from /usr/lib64/libpython2.7.so.1.0
#88 0x00007ffff7c2a1f3 in PyObject_Call () from /usr/lib64/libpython2.7.so.1.0
#89 0x00007ffff7c99c05 in PyEval_EvalFrameEx () from /usr/lib64/libpython2.7.so.1.0
#90 0x00007ffff7c94f37 in PyEval_EvalFrameEx () from /usr/lib64/libpython2.7.so.1.0
#91 0x00007ffff7c9392c in PyEval_EvalCodeEx () from /usr/lib64/libpython2.7.so.1.0
#92 0x00007ffff7c9a203 in PyEval_EvalFrameEx () from /usr/lib64/libpython2.7.so.1.0
#93 0x00007ffff7c9392c in PyEval_EvalCodeEx () from /usr/lib64/libpython2.7.so.1.0
#94 0x00007ffff7c99d44 in PyEval_EvalFrameEx () from /usr/lib64/libpython2.7.so.1.0
#95 0x00007ffff7c94f37 in PyEval_EvalFrameEx () from /usr/lib64/libpython2.7.so.1.0
#96 0x00007ffff7c9392c in PyEval_EvalCodeEx () from /usr/lib64/libpython2.7.so.1.0
#97 0x00007ffff7c99d44 in PyEval_EvalFrameEx () from /usr/lib64/libpython2.7.so.1.0
#98 0x00007ffff7c9392c in PyEval_EvalCodeEx () from /usr/lib64/libpython2.7.so.1.0
#99 0x00007ffff7c99d44 in PyEval_EvalFrameEx () from /usr/lib64/libpython2.7.so.1.0
--Type <RET> for more, q to quit, c to continue without paging--c
#100 0x00007ffff7c94f37 in PyEval_EvalFrameEx () from /usr/lib64/libpython2.7.so.1.0
#101 0x00007ffff7c94f37 in PyEval_EvalFrameEx () from /usr/lib64/libpython2.7.so.1.0
#102 0x00007ffff7c9392c in PyEval_EvalCodeEx () from /usr/lib64/libpython2.7.so.1.0
#103 0x00007ffff7c4192f in ?? () from /usr/lib64/libpython2.7.so.1.0
#104 0x00007ffff7c2a1f3 in PyObject_Call () from /usr/lib64/libpython2.7.so.1.0
#105 0x00007ffff7c34fb6 in ?? () from /usr/lib64/libpython2.7.so.1.0
#106 0x00007ffff7c2a1f3 in PyObject_Call () from /usr/lib64/libpython2.7.so.1.0
#107 0x00007ffff7c72e32 in ?? () from /usr/lib64/libpython2.7.so.1.0
#108 0x00007ffff7c70aa4 in ?? () from /usr/lib64/libpython2.7.so.1.0
#109 0x00007ffff7c2a1f3 in PyObject_Call () from /usr/lib64/libpython2.7.so.1.0
#110 0x00007ffff7c99c05 in PyEval_EvalFrameEx () from /usr/lib64/libpython2.7.so.1.0
#111 0x00007ffff7c94f37 in PyEval_EvalFrameEx () from /usr/lib64/libpython2.7.so.1.0
#112 0x00007ffff7c94f37 in PyEval_EvalFrameEx () from /usr/lib64/libpython2.7.so.1.0
#113 0x00007ffff7c94f37 in PyEval_EvalFrameEx () from /usr/lib64/libpython2.7.so.1.0
#114 0x00007ffff7c94f37 in PyEval_EvalFrameEx () from /usr/lib64/libpython2.7.so.1.0
#115 0x00007ffff7c9392c in PyEval_EvalCodeEx () from /usr/lib64/libpython2.7.so.1.0
#116 0x00007ffff7c4192f in ?? () from /usr/lib64/libpython2.7.so.1.0
#117 0x00007ffff7c2a1f3 in PyObject_Call () from /usr/lib64/libpython2.7.so.1.0
#118 0x00007ffff7c97666 in PyEval_EvalFrameEx () from /usr/lib64/libpython2.7.so.1.0
#119 0x00007ffff7c9392c in PyEval_EvalCodeEx () from /usr/lib64/libpython2.7.so.1.0
#120 0x00007ffff7c9a203 in PyEval_EvalFrameEx () from /usr/lib64/libpython2.7.so.1.0
#121 0x00007ffff7c9392c in PyEval_EvalCodeEx () from /usr/lib64/libpython2.7.so.1.0
#122 0x00007ffff7cfeab6 in PyEval_EvalCode () from /usr/lib64/libpython2.7.so.1.0
#123 0x00007ffff7d0552f in ?? () from /usr/lib64/libpython2.7.so.1.0
#124 0x00007ffff7d054d4 in PyRun_FileExFlags () from /usr/lib64/libpython2.7.so.1.0
#125 0x00007ffff7d052e8 in PyRun_SimpleFileExFlags () from /usr/lib64/libpython2.7.so.1.0
#126 0x00007ffff7d0b10b in Py_Main () from /usr/lib64/libpython2.7.so.1.0
#127 0x00007ffff75d7feb in __libc_start_main () from /lib64/libc.so.6
#128 0x000055555555508a in _start ()
(gdb)
```
Full gdb session

**Comment by dirkmueller** [comment]
The same crash happens in Python 3.6.x. so this is not python 2.x specific as indicated before.
