### ISSUE TITLE
1.3.6 broken on windows py2

### ISSUE THREAD

**Issue by kalemas** [Kronuz/pyScss#393]
Hello i encountered that my build broken, probably because of just released pyScss
<details>
    <summary>Log</summary>

```
> pip install pyScss
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting pyscss
Using cached pyScss-1.3.6.tar.gz (121 kB)
Collecting six
Using cached six-1.14.0-py2.py3-none-any.whl (10 kB)
Collecting enum34
Using cached enum34-1.1.10-py2-none-any.whl (11 kB)
Processing c:\users\kalem\appdata\local\pip\cache\wheels\46\37\4f\332bcea757140ff34e14dec7be65931f544c7ac94eb671ae9f\pathlib-1.0.1-py2-none-any.whl
Building wheels for collected packages: pyscss
Building wheel for pyscss (setup.py) ... error
ERROR: Command errored out with exit status 1:
command: 'C:\Users\kalem\.virtualenvs\ss\Scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'c:\\users\\kalem\\appdata\\local\\temp\\pip-install-hat08l\\pyscss\\setup.py'"'"'; __file__='"'"'c:\\users\\kalem\\appdata\\local\\temp\\pip-install-hat08l\\pyscss\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'c:\users\kalem\appdata\local\temp\pip-wheel-z0k4sg'
    cwd: c:\users\kalem\appdata\local\temp\pip-install-hat08l\pyscss\
Complete output (92 lines):
running bdist_wheel
running build
running build_py
creating build
creating build\lib.win-amd64-2.7
creating build\lib.win-amd64-2.7\scss
copying scss\ast.py -> build\lib.win-amd64-2.7\scss
copying scss\calculator.py -> build\lib.win-amd64-2.7\scss
copying scss\compiler.py -> build\lib.win-amd64-2.7\scss
copying scss\config.py -> build\lib.win-amd64-2.7\scss
copying scss\cssdefs.py -> build\lib.win-amd64-2.7\scss
copying scss\errors.py -> build\lib.win-amd64-2.7\scss
copying scss\legacy.py -> build\lib.win-amd64-2.7\scss
copying scss\less2scss.py -> build\lib.win-amd64-2.7\scss
copying scss\namespace.py -> build\lib.win-amd64-2.7\scss
copying scss\rule.py -> build\lib.win-amd64-2.7\scss
copying scss\scss_meta.py -> build\lib.win-amd64-2.7\scss
copying scss\selector.py -> build\lib.win-amd64-2.7\scss
copying scss\setup.py -> build\lib.win-amd64-2.7\scss
copying scss\source.py -> build\lib.win-amd64-2.7\scss
copying scss\tool.py -> build\lib.win-amd64-2.7\scss
copying scss\types.py -> build\lib.win-amd64-2.7\scss
copying scss\util.py -> build\lib.win-amd64-2.7\scss
copying scss\__init__.py -> build\lib.win-amd64-2.7\scss
copying scss\__main__.py -> build\lib.win-amd64-2.7\scss
creating build\lib.win-amd64-2.7\scss\extension
copying scss\extension\api.py -> build\lib.win-amd64-2.7\scss\extension
copying scss\extension\bootstrap.py -> build\lib.win-amd64-2.7\scss\extension
copying scss\extension\core.py -> build\lib.win-amd64-2.7\scss\extension
copying scss\extension\extra.py -> build\lib.win-amd64-2.7\scss\extension
copying scss\extension\fonts.py -> build\lib.win-amd64-2.7\scss\extension
copying scss\extension\__init__.py -> build\lib.win-amd64-2.7\scss\extension
creating build\lib.win-amd64-2.7\scss\extension\compass
copying scss\extension\compass\gradients.py -> build\lib.win-amd64-2.7\scss\extension\compass
copying scss\extension\compass\helpers.py -> build\lib.win-amd64-2.7\scss\extension\compass
copying scss\extension\compass\images.py -> build\lib.win-amd64-2.7\scss\extension\compass
copying scss\extension\compass\layouts.py -> build\lib.win-amd64-2.7\scss\extension\compass
copying scss\extension\compass\sprites.py -> build\lib.win-amd64-2.7\scss\extension\compass
copying scss\extension\compass\__init__.py -> build\lib.win-amd64-2.7\scss\extension\compass
creating build\lib.win-amd64-2.7\scss\grammar
copying scss\grammar\expression.py -> build\lib.win-amd64-2.7\scss\grammar
copying scss\grammar\scanner.py -> build\lib.win-amd64-2.7\scss\grammar
copying scss\grammar\__init__.py -> build\lib.win-amd64-2.7\scss\grammar
running build_ext
building 'scss.grammar._scanner' extension
==========================================================================
WARNING: The C extension could not be compiled, speedups are not enabled.
Failure information, if any, is above.
Retrying the build without the C extension now.

running bdist_wheel
running build
running build_py
running build_ext
building 'scss.grammar._scanner' extension
Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "c:\users\kalem\appdata\local\temp\pip-install-hat08l\pyscss\setup.py", line 154, in <module>
    try_building_extension()
    File "c:\users\kalem\appdata\local\temp\pip-install-hat08l\pyscss\setup.py", line 140, in try_building_extension
    run_setup(False)
    File "c:\users\kalem\appdata\local\temp\pip-install-hat08l\pyscss\setup.py", line 122, in run_setup
    **extra_opts
    File "C:\Users\kalem\.virtualenvs\ss\lib\site-packages\setuptools\__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
    File "c:\python27\lib\distutils\core.py", line 151, in setup
    dist.run_commands()
    File "c:\python27\lib\distutils\dist.py", line 953, in run_commands
    self.run_command(cmd)
    File "c:\python27\lib\distutils\dist.py", line 972, in run_command
    cmd_obj.run()
    File "C:\Users\kalem\.virtualenvs\ss\lib\site-packages\wheel\bdist_wheel.py", line 223, in run
    self.run_command('build')
    File "c:\python27\lib\distutils\cmd.py", line 326, in run_command
    self.distribution.run_command(command)
    File "c:\python27\lib\distutils\dist.py", line 972, in run_command
    cmd_obj.run()
    File "c:\python27\lib\distutils\command\build.py", line 127, in run
    self.run_command(cmd_name)
    File "c:\python27\lib\distutils\cmd.py", line 326, in run_command
    self.distribution.run_command(command)
    File "c:\python27\lib\distutils\dist.py", line 972, in run_command
    cmd_obj.run()
    File "c:\users\kalem\appdata\local\temp\pip-install-hat08l\pyscss\setup.py", line 57, in run
    build_ext.run(self)
    File "c:\python27\lib\distutils\command\build_ext.py", line 340, in run
    self.build_extensions()
    File "c:\python27\lib\distutils\command\build_ext.py", line 449, in build_extensions
    self.build_extension(ext)
    File "c:\users\kalem\appdata\local\temp\pip-install-hat08l\pyscss\setup.py", line 65, in build_extension
    raise BuildFailed()
__main__.BuildFailed
----------------------------------------
ERROR: Failed building wheel for pyscss
Running setup.py clean for pyscss
Failed to build pyscss
Installing collected packages: six, enum34, pathlib, pyscss
    Running setup.py install for pyscss ... error
    ERROR: Command errored out with exit status 1:
    command: 'C:\Users\kalem\.virtualenvs\ss\Scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'c:\\users\\kalem\\appdata\\local\\temp\\pip-install-hat08l\\pyscss\\setup.py'"'"'; __file__='"'"'c:\\users\\kalem\\appdata\\local\\temp\\pip-install-hat08l\\pyscss\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'c:\users\kalem\appdata\local\temp\pip-record-zl9yhu\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\kalem\.virtualenvs\ss\include\site\python2.7\pyscss'
        cwd: c:\users\kalem\appdata\local\temp\pip-install-hat08l\pyscss\
    Complete output (94 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-2.7
    creating build\lib.win-amd64-2.7\scss
    copying scss\ast.py -> build\lib.win-amd64-2.7\scss
    copying scss\calculator.py -> build\lib.win-amd64-2.7\scss
    copying scss\compiler.py -> build\lib.win-amd64-2.7\scss
    copying scss\config.py -> build\lib.win-amd64-2.7\scss
    copying scss\cssdefs.py -> build\lib.win-amd64-2.7\scss
    copying scss\errors.py -> build\lib.win-amd64-2.7\scss
    copying scss\legacy.py -> build\lib.win-amd64-2.7\scss
    copying scss\less2scss.py -> build\lib.win-amd64-2.7\scss
    copying scss\namespace.py -> build\lib.win-amd64-2.7\scss
    copying scss\rule.py -> build\lib.win-amd64-2.7\scss
    copying scss\scss_meta.py -> build\lib.win-amd64-2.7\scss
    copying scss\selector.py -> build\lib.win-amd64-2.7\scss
    copying scss\setup.py -> build\lib.win-amd64-2.7\scss
    copying scss\source.py -> build\lib.win-amd64-2.7\scss
    copying scss\tool.py -> build\lib.win-amd64-2.7\scss
    copying scss\types.py -> build\lib.win-amd64-2.7\scss
    copying scss\util.py -> build\lib.win-amd64-2.7\scss
    copying scss\__init__.py -> build\lib.win-amd64-2.7\scss
    copying scss\__main__.py -> build\lib.win-amd64-2.7\scss
    creating build\lib.win-amd64-2.7\scss\extension
    copying scss\extension\api.py -> build\lib.win-amd64-2.7\scss\extension
    copying scss\extension\bootstrap.py -> build\lib.win-amd64-2.7\scss\extension
    copying scss\extension\core.py -> build\lib.win-amd64-2.7\scss\extension
    copying scss\extension\extra.py -> build\lib.win-amd64-2.7\scss\extension
    copying scss\extension\fonts.py -> build\lib.win-amd64-2.7\scss\extension
    copying scss\extension\__init__.py -> build\lib.win-amd64-2.7\scss\extension
    creating build\lib.win-amd64-2.7\scss\extension\compass
    copying scss\extension\compass\gradients.py -> build\lib.win-amd64-2.7\scss\extension\compass
    copying scss\extension\compass\helpers.py -> build\lib.win-amd64-2.7\scss\extension\compass
    copying scss\extension\compass\images.py -> build\lib.win-amd64-2.7\scss\extension\compass
    copying scss\extension\compass\layouts.py -> build\lib.win-amd64-2.7\scss\extension\compass
    copying scss\extension\compass\sprites.py -> build\lib.win-amd64-2.7\scss\extension\compass
    copying scss\extension\compass\__init__.py -> build\lib.win-amd64-2.7\scss\extension\compass
    creating build\lib.win-amd64-2.7\scss\grammar
    copying scss\grammar\expression.py -> build\lib.win-amd64-2.7\scss\grammar
    copying scss\grammar\scanner.py -> build\lib.win-amd64-2.7\scss\grammar
    copying scss\grammar\__init__.py -> build\lib.win-amd64-2.7\scss\grammar
    running build_ext
    building 'scss.grammar._scanner' extension
    ==========================================================================
    WARNING: The C extension could not be compiled, speedups are not enabled.
    Failure information, if any, is above.
    Retrying the build without the C extension now.

    running install
    running build
    running build_py
    running build_ext
    building 'scss.grammar._scanner' extension
    Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "c:\users\kalem\appdata\local\temp\pip-install-hat08l\pyscss\setup.py", line 154, in <module>
        try_building_extension()
    File "c:\users\kalem\appdata\local\temp\pip-install-hat08l\pyscss\setup.py", line 140, in try_building_extension
        run_setup(False)
    File "c:\users\kalem\appdata\local\temp\pip-install-hat08l\pyscss\setup.py", line 122, in run_setup
        **extra_opts
    File "C:\Users\kalem\.virtualenvs\ss\lib\site-packages\setuptools\__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
    File "c:\python27\lib\distutils\core.py", line 151, in setup
        dist.run_commands()
    File "c:\python27\lib\distutils\dist.py", line 953, in run_commands
        self.run_command(cmd)
    File "c:\python27\lib\distutils\dist.py", line 972, in run_command
        cmd_obj.run()
    File "C:\Users\kalem\.virtualenvs\ss\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
    File "c:\python27\lib\distutils\command\install.py", line 563, in run
        self.run_command('build')
    File "c:\python27\lib\distutils\cmd.py", line 326, in run_command
        self.distribution.run_command(command)
    File "c:\python27\lib\distutils\dist.py", line 972, in run_command
        cmd_obj.run()
    File "c:\python27\lib\distutils\command\build.py", line 127, in run
        self.run_command(cmd_name)
    File "c:\python27\lib\distutils\cmd.py", line 326, in run_command
        self.distribution.run_command(command)
    File "c:\python27\lib\distutils\dist.py", line 972, in run_command
        cmd_obj.run()
    File "c:\users\kalem\appdata\local\temp\pip-install-hat08l\pyscss\setup.py", line 57, in run
        build_ext.run(self)
    File "c:\python27\lib\distutils\command\build_ext.py", line 340, in run
        self.build_extensions()
    File "c:\python27\lib\distutils\command\build_ext.py", line 449, in build_extensions
        self.build_extension(ext)
    File "c:\users\kalem\appdata\local\temp\pip-install-hat08l\pyscss\setup.py", line 65, in build_extension
        raise BuildFailed()
    __main__.BuildFailed
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\kalem\.virtualenvs\ss\Scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'c:\\users\\kalem\\appdata\\local\\temp\\pip-install-hat08l\\pyscss\\setup.py'"'"'; __file__='"'"'c:\\users\\kalem\\appdata\\local\\temp\\pip-install-hat08l\\pyscss\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'c:\users\kalem\appdata\local\temp\pip-record-zl9yhu\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\kalem\.virtualenvs\ss\include\site\python2.7\pyscss' Check the logs for full command output
```

</details>

1.3.5 installs just ok

**Comment by stuertz** [comment]
I'm seeing something similar while building the conda-forge packages:
https://github.com/conda-forge/pyscss-feedstock/pull/10

```
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -ID:\bld\pyscss_1584879055273\_h_env\include -ID:\bld\pyscss_1584879055273\_h_env\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt" -ID:\bld\pyscss_1584879055273\_h_env\Library\include -ID:\bld\pyscss_1584879055273\_h_env\Library\include /Tcscss/src/hashtable.c /Fobuild\temp.win-amd64-3.8\Release\scss/src/hashtable.obj
  hashtable.c
  scss/src/hashtable.c(46): error C2036: 'const void *': unknown size
  Traceback (most recent call last):
    File "D:\bld\pyscss_1584879055273\_h_env\lib\distutils\_msvccompiler.py", line 438, in compile
      self.spawn(args)
    File "D:\bld\pyscss_1584879055273\_h_env\lib\distutils\_msvccompiler.py", line 557, in spawn
      return super().spawn(cmd)
    File "D:\bld\pyscss_1584879055273\_h_env\lib\distutils\ccompiler.py", line 910, in spawn
      spawn(cmd, dry_run=self.dry_run)
    File "D:\bld\pyscss_1584879055273\_h_env\lib\distutils\spawn.py", line 38, in spawn
      _spawn_nt(cmd, search_path, dry_run=dry_run)
    File "D:\bld\pyscss_1584879055273\_h_env\lib\distutils\spawn.py", line 80, in _spawn_nt
      raise DistutilsExecError(
  distutils.errors.DistutilsExecError: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\amd64\\cl.exe' failed with exit status 2
```

**Comment by e0ne** [comment]
@kalemas @stuertz thanks for the bug report. Do you able to reproduce this issue with py3 too?

**Comment by stuertz** [comment]
what do you mean with "py3"?
As you can see in the linked ci build.- Builds are failing with py36, 37 and 38 on windows. Earlier versions are currently not supported with conda any more. I think it is related to more stricter code checking with VS14 compiler.  See also https://stackoverflow.com/questions/37460579/error-c2036-void-unknown-size
Maybe there is a new/better implementation for your hashtab available ;-)

**Comment by djowett-ftw** [comment]
Also seeing problems with Py2 on Mac.  Was Python 2 support deliberately dropped?  If so, did you really mean to do it in a patch release?

https://github.com/Kronuz/pyScss/commit/8d21af7273078a46493468b298d23e8d1a495189

**Comment by NotSqrt** [comment]
In linux, my builds were broken with v1.3.6, but the error message is more explicit:

```
In file included from scss/src/_speedups.c:14:0:
    scss/src/scanner.h:17:18: fatal error: pcre.h: No such file or directory
```


`pcre.h` is needed (package `libpcre3-dev` in debian derivatives).

**Comment by e0ne** [comment]
@djowett-ftw  py2 testing was dropped because TravisCI doesn't support it anymore:(.  There is no big difference in a python code with a previous release https://github.com/Kronuz/pyScss/compare/v1.3.5...1.3.6 so I suspect it should work.  I'm able to run py27 tests on my mac env

**Comment by e0ne** [comment]
@NotSqrt it looks like v1.3.5 didn't build C-extension:(. I'm investigating this issue now

**Comment by e0ne** [comment]
@kalemas, @stuertz,  @djowett-ftw,  @NotSqrt  could you please verify that #394 fixes this issue, so I'll release a new version?

**Comment by NotSqrt** [comment]
@e0ne 
`pip install https://github.com/e0ne/pyScss/archive/optional-build.zip` fails if `libpcre3-dev` is not installed in my ubuntu 18.04.

<details>
  <summary>Logs</summary>

```
Building wheels for collected packages: pyScss
  Running setup.py bdist_wheel for pyScss ... error
  Complete output from command /path/ve/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-piK0JG-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpf0Gnsapip-wheel- --python-tag cp27:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-2.7
  creating build/lib.linux-x86_64-2.7/scss
  copying scss/cssdefs.py -> build/lib.linux-x86_64-2.7/scss
  copying scss/calculator.py -> build/lib.linux-x86_64-2.7/scss
  copying scss/legacy.py -> build/lib.linux-x86_64-2.7/scss
  copying scss/config.py -> build/lib.linux-x86_64-2.7/scss
  copying scss/less2scss.py -> build/lib.linux-x86_64-2.7/scss
  copying scss/types.py -> build/lib.linux-x86_64-2.7/scss
  copying scss/source.py -> build/lib.linux-x86_64-2.7/scss
  copying scss/namespace.py -> build/lib.linux-x86_64-2.7/scss
  copying scss/scss_meta.py -> build/lib.linux-x86_64-2.7/scss
  copying scss/selector.py -> build/lib.linux-x86_64-2.7/scss
  copying scss/errors.py -> build/lib.linux-x86_64-2.7/scss
  copying scss/tool.py -> build/lib.linux-x86_64-2.7/scss
  copying scss/__main__.py -> build/lib.linux-x86_64-2.7/scss
  copying scss/__init__.py -> build/lib.linux-x86_64-2.7/scss
  copying scss/compiler.py -> build/lib.linux-x86_64-2.7/scss
  copying scss/setup.py -> build/lib.linux-x86_64-2.7/scss
  copying scss/ast.py -> build/lib.linux-x86_64-2.7/scss
  copying scss/util.py -> build/lib.linux-x86_64-2.7/scss
  copying scss/rule.py -> build/lib.linux-x86_64-2.7/scss
  creating build/lib.linux-x86_64-2.7/scss/extension
  copying scss/extension/api.py -> build/lib.linux-x86_64-2.7/scss/extension
  copying scss/extension/fonts.py -> build/lib.linux-x86_64-2.7/scss/extension
  copying scss/extension/core.py -> build/lib.linux-x86_64-2.7/scss/extension
  copying scss/extension/extra.py -> build/lib.linux-x86_64-2.7/scss/extension
  copying scss/extension/__init__.py -> build/lib.linux-x86_64-2.7/scss/extension
  copying scss/extension/bootstrap.py -> build/lib.linux-x86_64-2.7/scss/extension
  creating build/lib.linux-x86_64-2.7/scss/extension/compass
  copying scss/extension/compass/layouts.py -> build/lib.linux-x86_64-2.7/scss/extension/compass
  copying scss/extension/compass/images.py -> build/lib.linux-x86_64-2.7/scss/extension/compass
  copying scss/extension/compass/sprites.py -> build/lib.linux-x86_64-2.7/scss/extension/compass
  copying scss/extension/compass/gradients.py -> build/lib.linux-x86_64-2.7/scss/extension/compass
  copying scss/extension/compass/helpers.py -> build/lib.linux-x86_64-2.7/scss/extension/compass
  copying scss/extension/compass/__init__.py -> build/lib.linux-x86_64-2.7/scss/extension/compass
  creating build/lib.linux-x86_64-2.7/scss/grammar
  copying scss/grammar/expression.py -> build/lib.linux-x86_64-2.7/scss/grammar
  copying scss/grammar/scanner.py -> build/lib.linux-x86_64-2.7/scss/grammar
  copying scss/grammar/__init__.py -> build/lib.linux-x86_64-2.7/scss/grammar
  running build_ext
  building 'scss.grammar._scanner' extension
  creating build/temp.linux-x86_64-2.7
  creating build/temp.linux-x86_64-2.7/scss
  creating build/temp.linux-x86_64-2.7/scss/src
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c scss/src/_speedups.c -o build/temp.linux-x86_64-2.7/scss/src/_speedups.o
  In file included from scss/src/_speedups.c:14:0:
  scss/src/scanner.h:17:18: fatal error: pcre.h: Aucun fichier ou dossier de ce type
  compilation terminated.
  ==========================================================================
  WARNING: The C extension could not be compiled, speedups are not enabled.
  Failure information, if any, is above.
  Retrying the build without the C extension now.

  running bdist_wheel
  running build
  running build_py
  running build_ext
  building 'scss.grammar._scanner' extension
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c scss/src/_speedups.c -o build/temp.linux-x86_64-2.7/scss/src/_speedups.o
  In file included from scss/src/_speedups.c:14:0:
  scss/src/scanner.h:17:18: fatal error: pcre.h: Aucun fichier ou dossier de ce type
  compilation terminated.
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-piK0JG-build/setup.py", line 155, in <module>
      try_building_extension()
    File "/tmp/pip-piK0JG-build/setup.py", line 141, in try_building_extension
      run_setup(False)
    File "/tmp/pip-piK0JG-build/setup.py", line 123, in run_setup
      **extra_opts
    File "/path/ve/local/lib/python2.7/site-packages/setuptools/__init__.py", line 145, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
      dist.run_commands()
    File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/path/ve/local/lib/python2.7/site-packages/wheel/bdist_wheel.py", line 223, in run
      self.run_command('build')
    File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/usr/lib/python2.7/distutils/command/build.py", line 128, in run
      self.run_command(cmd_name)
    File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/tmp/pip-piK0JG-build/setup.py", line 56, in run
      build_ext.run(self)
    File "/usr/lib/python2.7/distutils/command/build_ext.py", line 339, in run
      self.build_extensions()
    File "/usr/lib/python2.7/distutils/command/build_ext.py", line 448, in build_extensions
      self.build_extension(ext)
    File "/tmp/pip-piK0JG-build/setup.py", line 64, in build_extension
      raise BuildFailed()
  __main__.BuildFailed

  ----------------------------------------
  Failed building wheel for pyScss
  Running setup.py clean for pyScss
Failed to build pyScss
```
</details>

**Comment by e0ne** [comment]
@NotSqrt thanks for the good test case! It should work now

**Comment by NotSqrt** [comment]
@e0ne yes, the command no longer fails !

**Comment by djowett-ftw** [comment]
@e0ne yes that works over here thanks (a Plone buildout on Python2.7)

**Comment by stuertz** [comment]
Thanks, works for the conda build also!
